name: Build with bob

on:
  push:
  workflow_dispatch:

env:
  DEFOLD_VERSION: '57b34efdf44a922acc6f21d285b207029b53927d'
  BUILD_SERVER: 'https://build.defold.com'

jobs:
  build_with_bob:
    strategy:
      matrix:
        platform: [x86_64-linux]
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Download bob.jar
        run: |
          wget -q http://d.defold.com/archive/stable/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456
      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}}
      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle
